/** Generate the published schemas and fixed runtime validators from one schema owner. */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { z } from 'zod';
import Ajv from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { buildSync } from 'esbuild';
import { chocoManifestSchema, chocoMotionSchema, chocoDocumentSchema, sceneSchema } from '../../src/codec/schema.ts';
mkdirSync('docs/spec', { recursive: true });
mkdirSync('src/codec/generated', { recursive: true });
const check = process.argv.includes('--check');
function output(path: string, contents: string) {
  if (!check) writeFileSync(path, contents);
  else if (readFileSync(path, 'utf8') !== contents)
    throw new Error(`Stale generated file: ${path}. Run npx tsx scripts/choco/write-spec.ts.`);
}
const schemas = Object.fromEntries([['manifest', chocoManifestSchema], ['scene', sceneSchema], ['motion', chocoMotionSchema], ['document', chocoDocumentSchema]].map(([name, schema]) => [name, z.toJSONSchema(schema, { target: 'draft-2020-12', io: 'output', reused: 'ref' })]));
for (const name of ['manifest', 'scene', 'motion']) output(`docs/spec/choco-${name}.schema.json`, JSON.stringify(schemas[name], null, 2) + '\n');
// Fixed output contract: defaults are materialized by the compiler. No coercion or mutation.
const ajv = new Ajv({ strict: true, ownProperties: true, messages: false, inlineRefs: false, discriminator: true, code: { source: true, esm: true, lines: true } });
ajv.addSchema(schemas.manifest, 'manifest');
// Zod's union discriminator selects exactly one object branch. Preserve that dispatch in
// generated code instead of validating every paint/program variant on each scene node.
// The published JSON Schemas remain standard oneOf schemas without Ajv annotations.
ajv.addSchema(z.toJSONSchema(chocoDocumentSchema, {
  target: 'draft-2020-12', io: 'output', reused: 'ref',
  override({ zodSchema, jsonSchema }) {
    if (zodSchema instanceof z.ZodDiscriminatedUnion) {
      jsonSchema.type = 'object';
      jsonSchema.discriminator = { propertyName: zodSchema.def.discriminator };
    }
  },
}), 'document');
// Ajv emits CommonJS imports for helpers even with ESM exports. Bundle those helpers
// here so the checked-in validator works in both native Node ESM and browser builds.
const validator = buildSync({
  stdin: { contents: standaloneCode(ajv, { validateManifest: 'manifest', validateDocument: 'document' }), resolveDir: process.cwd(), sourcefile: 'choco-validator.js' },
  bundle: true, format: 'esm', platform: 'neutral', write: false,
}).outputFiles[0].text;
output('src/codec/generated/validate.js', '// Generated by scripts/choco/write-spec.ts. Do not edit.\n' + validator);
output('src/codec/generated/validate.d.ts', `import type { ChocoDocument, ChocoManifest } from '../schema.ts';\nexport function validateManifest(value: unknown): value is ChocoManifest;\nexport function validateDocument(value: unknown): value is ChocoDocument;\n`);
